// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_SharedResources.Screens.iPhone.Battery {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("BatteryStatusScreen")]
	public partial class BatteryStatusScreen {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIProgressView __mt_barBatteryLevel;
		
		private MonoTouch.UIKit.UILabel __mt_lblBatteryState;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("barBatteryLevel")]
		private MonoTouch.UIKit.UIProgressView barBatteryLevel {
			get {
				this.__mt_barBatteryLevel = ((MonoTouch.UIKit.UIProgressView)(this.GetNativeField("barBatteryLevel")));
				return this.__mt_barBatteryLevel;
			}
			set {
				this.__mt_barBatteryLevel = value;
				this.SetNativeField("barBatteryLevel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblBatteryState")]
		private MonoTouch.UIKit.UILabel lblBatteryState {
			get {
				this.__mt_lblBatteryState = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lblBatteryState")));
				return this.__mt_lblBatteryState;
			}
			set {
				this.__mt_lblBatteryState = value;
				this.SetNativeField("lblBatteryState", value);
			}
		}
	}
}
