// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_SharedResources.Screens.iPhone.Photos {
	
	
	// Base type probably should be UIKit.UIViewController or subclass
	[Foundation.Register("CustomCameraViewScreen")]
	public partial class CustomCameraViewScreen {
		
		private UIKit.UIView __mt_view;
		
		private UIKit.UIButton __mt_btnTakePhoto;
		
		private UIKit.UIImageView __mt_imgPhoto;
		
		#pragma warning disable 0169
		[Foundation.Connect("view")]
		private UIKit.UIView view {
			get {
				this.__mt_view = ((UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[Foundation.Connect("btnTakePhoto")]
		private UIKit.UIButton btnTakePhoto {
			get {
				this.__mt_btnTakePhoto = ((UIKit.UIButton)(this.GetNativeField("btnTakePhoto")));
				return this.__mt_btnTakePhoto;
			}
			set {
				this.__mt_btnTakePhoto = value;
				this.SetNativeField("btnTakePhoto", value);
			}
		}
		
		[Foundation.Connect("imgPhoto")]
		private UIKit.UIImageView imgPhoto {
			get {
				this.__mt_imgPhoto = ((UIKit.UIImageView)(this.GetNativeField("imgPhoto")));
				return this.__mt_imgPhoto;
			}
			set {
				this.__mt_imgPhoto = value;
				this.SetNativeField("imgPhoto", value);
			}
		}
	}
}
