// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_SharedResources.Screens.iPhone.Photos {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("CustomCameraViewScreen")]
	public partial class CustomCameraViewScreen {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_btnTakePhoto;
		
		private MonoTouch.UIKit.UIImageView __mt_imgPhoto;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnTakePhoto")]
		private MonoTouch.UIKit.UIButton btnTakePhoto {
			get {
				this.__mt_btnTakePhoto = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnTakePhoto")));
				return this.__mt_btnTakePhoto;
			}
			set {
				this.__mt_btnTakePhoto = value;
				this.SetNativeField("btnTakePhoto", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imgPhoto")]
		private MonoTouch.UIKit.UIImageView imgPhoto {
			get {
				this.__mt_imgPhoto = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imgPhoto")));
				return this.__mt_imgPhoto;
			}
			set {
				this.__mt_imgPhoto = value;
				this.SetNativeField("imgPhoto", value);
			}
		}
	}
}
