// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CloudKitAtlas
{
	public partial class MainMenuTableViewController : UITableViewController
	{
		public CodeSampleGroup [] CodeSampleGroups { get; set; }

		public MainMenuTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
