// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CloudKitAtlas
{
	public partial class SubmenuTableViewCell : UITableViewCell
	{
		public SubmenuTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
