// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CloudKitAtlas
{
	public partial class SubmenuTableViewController : UITableViewController
	{
		public string GroupTitle { get; set; }
		public CodeSample [] CodeSamples { get; set; }

		public SubmenuTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
