// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_StandardControls.Screens.iPhone.Switches {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("Switches_iPhone")]
	public partial class Switches_iPhone {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UISwitch __mt_swchOne;
		
		private MonoTouch.UIKit.UISwitch __mt_swchTwo;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("swchOne")]
		private MonoTouch.UIKit.UISwitch swchOne {
			get {
				this.__mt_swchOne = ((MonoTouch.UIKit.UISwitch)(this.GetNativeField("swchOne")));
				return this.__mt_swchOne;
			}
			set {
				this.__mt_swchOne = value;
				this.SetNativeField("swchOne", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("swchTwo")]
		private MonoTouch.UIKit.UISwitch swchTwo {
			get {
				this.__mt_swchTwo = ((MonoTouch.UIKit.UISwitch)(this.GetNativeField("swchTwo")));
				return this.__mt_swchTwo;
			}
			set {
				this.__mt_swchTwo = value;
				this.SetNativeField("swchTwo", value);
			}
		}
	}
}
