// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CloudKitAtlas
{
	public partial class CodeSampleViewController : UIViewController
	{
		public string GroupTitle { get; set; }
		public CodeSample SelectedCodeSample { get; set; }

		public CodeSampleViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
