// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using UIKit;
using CoreFoundation;

namespace ScanningAndDetecting3DObjects
{
	internal class Message
	{
		internal NSMutableAttributedString Text 
		{
			get;
		}

		internal Message(string body, string title = "")
		{
			if (title != null)
			{
				// make the title bold
				Text = new NSMutableAttributedString($"{title}\n{body}");
				var titleRange = new NSRange(0, title.Length);
				Text.AddAttribute(new NSString("NSFont"), UIFont.BoldSystemFontOfSize(17), titleRange);
			}
			else
			{
				Text = new NSMutableAttributedString(body);
			}
		}

		void PrintToConsole()
		{
			Console.WriteLine(Text.Value);
		}
	}

	internal partial class MessageLabel : UILabel
	{
		internal MessageLabel (IntPtr handle) : base (handle)
		{
		}

		public override CGSize IntrinsicContentSize
		{
			get
			{
				var contentSize = base.IntrinsicContentSize;
				contentSize.Width += 20;
				contentSize.Height += 20;
				return contentSize;
			}
		}

		internal void Display(Message msg)
		{
			DispatchQueue.MainQueue.DispatchAsync(() =>
			{
				AttributedText = msg.Text;
				Hidden = false;
			});
		}

		internal void Clear()
		{
			DispatchQueue.MainQueue.DispatchAsync(() =>
			{
				// Note that setting `Text` clears `AttributedText`
				Text = "";
				Hidden = true;
			});
		}
	}
}
