// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ScanningAndDetecting3DObjects {
	internal partial class RoundedButton : UIButton {
		internal RoundedButton (IntPtr handle) : base (handle)
		{
			Setup ();
		}

		protected void Setup ()
		{
			BackgroundColor = Utilities.AppBlue;
			Layer.CornerRadius = 8;
			ClipsToBounds = true;
			SetTitleColor (UIColor.White, UIControlState.Normal);
			TitleLabel.Font = UIFont.BoldSystemFontOfSize (17);
		}

		public override bool Enabled {
			get => base.Enabled;
			set {
				base.Enabled = value;
				BackgroundColor = value ? Utilities.AppBlue : Utilities.AppGray;
			}
		}

		private bool toggledOn;
		internal bool ToggledOn {
			get => toggledOn;
			set {
				toggledOn = value;
				if (!value) {
					BackgroundColor = Utilities.AppGray;
					return;
				}
				BackgroundColor = value ? Utilities.AppBlue : Utilities.AppLightBlue;
			}
		}
	}
}
