// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Chat
{
	public partial class IncomingCell : BubbleCell
	{
		static UIImage bubble;
		protected override UIImage BubbleImg {
			get {
				return bubble;
			}
		}

		static UIImage highlightedBubble;
		protected override UIImage BubbleHighlightedImage {
			get {
				return highlightedBubble;
			}
		}

		public override UIImageView BubbleView {
			get {
				// from outlet
				return BubbleImageView;
			}
		}

		protected override UILabel MessageLbl {
			get {
				// from outlet
				return MessageText;
			}
		}

		public IncomingCell (IntPtr handle)
			: base (handle)
		{
			// TODO: move to static ctor
			if (bubble == null && highlightedBubble == null) {
				UIImage mask = UIImage.FromBundle ("MessageBubble");
				mask = new UIImage (mask.CGImage, mask.CurrentScale, UIImageOrientation.UpMirrored);

				var cap = new UIEdgeInsets {
					Top = 17,
					Left = (float)26.5,
					Bottom = (float)17.5,
					Right = 21,
				};

				var color = UIColor.FromRGB (229, 229, 234);
				bubble = CreateColoredImage (color, mask).CreateResizableImage (cap);

				var highlightedColor = UIColor.FromRGB (206, 206, 210);
				highlightedBubble = CreateColoredImage (highlightedColor, mask).CreateResizableImage (cap);
			}
		}
	}
}
