// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Chat
{
	public partial class IncomingCell : UITableViewCell
	{
		public override UILabel TextLabel {
			get {
				return MessageText;
			}
		}

		public IncomingCell (IntPtr handle)
			: base (handle)
		{
		}
	}
}
