// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FontList.Screens.iPhone.FontViewer {
	
	
	// Base type probably should be UIKit.UIViewController or subclass
	[Foundation.Register("FontViewerScreen_iPhone")]
	public partial class FontViewerScreen_iPhone {
		
		private UIKit.UIView __mt_view;
		
		private UIKit.UITextView __mt_txtMain;
		
		#pragma warning disable 0169
		[Foundation.Connect("view")]
		private UIKit.UIView view {
			get {
				this.__mt_view = ((UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[Foundation.Connect("txtMain")]
		private UIKit.UITextView txtMain {
			get {
				this.__mt_txtMain = ((UIKit.UITextView)(this.GetNativeField("txtMain")));
				return this.__mt_txtMain;
			}
			set {
				this.__mt_txtMain = value;
				this.SetNativeField("txtMain", value);
			}
		}
	}
}
