global using AVFoundation;
global using CoreFoundation;
global using CoreImage;
global using CoreVideo;
global using ObjCRuntime;
global using ImageIO;
global using Photos;
global using Vision;
global using VisionObjectTrack.Enums;
