// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace tvTable {
	/// <summary>
	/// The View used as the Details section of the Spilt View to display detailed information
	/// about the Row highlighted in the Master section.
	/// </summary>
	public partial class AttractionView : UIView {
		#region Constructors
		/// <summary>
		/// Initializes a new instance of the <see cref="T:tvTable.AttractionView"/> class.
		/// </summary>
		/// <param name="handle">Handle.</param>
		public AttractionView (IntPtr handle) : base (handle)
		{
		}
		#endregion
	}
}
