// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace avTouch {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("avTouchViewController")]
	public partial class avTouchViewController {
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				return ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
			}
			set {
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("controller")]
		private avTouchController controller {
			get {
				return ((avTouchController)(this.GetNativeField("controller")));
			}
			set {
				this.SetNativeField("controller", value);
			}
		}
	}
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("avTouchController")]
	public partial class avTouchController {
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Export("volumeSliderMoved:")]
		partial void volumeSliderMoved (MonoTouch.UIKit.UISlider sender);

		[MonoTouch.Foundation.Export("progressSliderMoved:")]
		partial void progressSliderMoved (MonoTouch.UIKit.UISlider sender);

		[MonoTouch.Foundation.Export("playButtonPressed:")]
		partial void playButtonPressed (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Export("ffwButtonReleased:")]
		partial void ffwButtonReleased (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Export("rewButtonReleased:")]
		partial void rewButtonReleased (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Export("rewButtonPressed:")]
		partial void rewButtonPressed (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Export("ffwButtonPressed:")]
		partial void ffwButtonPressed (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Connect("_playButton")]
		private MonoTouch.UIKit.UIButton _playButton {
			get {
				return ((MonoTouch.UIKit.UIButton)(this.GetNativeField("_playButton")));
			}
			set {
				this.SetNativeField("_playButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("_rewButton")]
		private MonoTouch.UIKit.UIButton _rewButton {
			get {
				return ((MonoTouch.UIKit.UIButton)(this.GetNativeField("_rewButton")));
			}
			set {
				this.SetNativeField("_rewButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("_ffwButton")]
		private MonoTouch.UIKit.UIButton _ffwButton {
			get {
				return ((MonoTouch.UIKit.UIButton)(this.GetNativeField("_ffwButton")));
			}
			set {
				this.SetNativeField("_ffwButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("_currentTime")]
		private MonoTouch.UIKit.UILabel _currentTime {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("_currentTime")));
			}
			set {
				this.SetNativeField("_currentTime", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("_duration")]
		private MonoTouch.UIKit.UILabel _duration {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("_duration")));
			}
			set {
				this.SetNativeField("_duration", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("_volumeSlider")]
		private MonoTouch.UIKit.UISlider _volumeSlider {
			get {
				return ((MonoTouch.UIKit.UISlider)(this.GetNativeField("_volumeSlider")));
			}
			set {
				this.SetNativeField("_volumeSlider", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("_progressBar")]
		private MonoTouch.UIKit.UISlider _progressBar {
			get {
				return ((MonoTouch.UIKit.UISlider)(this.GetNativeField("_progressBar")));
			}
			set {
				this.SetNativeField("_progressBar", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("_fileName")]
		private MonoTouch.UIKit.UILabel _fileName {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("_fileName")));
			}
			set {
				this.SetNativeField("_fileName", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("_lvlMeter_in")]
		private CALevelMeter _lvlMeter_in {
			get {
				return ((CALevelMeter)(this.GetNativeField("_lvlMeter_in")));
			}
			set {
				this.SetNativeField("_lvlMeter_in", value);
			}
		}
	}
	
	// Base type probably should be MonoTouch.UIKit.UIView or subclass
	[MonoTouch.Foundation.Register("CALevelMeter")]
	public partial class CALevelMeter {
	}
}
