// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace avTouch {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("avTouchViewController")]
	public partial class avTouchViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private avTouchController __mt_controller;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("controller")]
		private avTouchController controller {
			get {
				this.__mt_controller = ((avTouchController)(this.GetNativeField("controller")));
				return this.__mt_controller;
			}
			set {
				this.__mt_controller = value;
				this.SetNativeField("controller", value);
			}
		}
	}
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("avTouchController")]
	public partial class avTouchController {
		
		private MonoTouch.UIKit.UIButton __mt__playButton;
		
		private MonoTouch.UIKit.UIButton __mt__rewButton;
		
		private MonoTouch.UIKit.UIButton __mt__ffwButton;
		
		private MonoTouch.UIKit.UILabel __mt__currentTime;
		
		private MonoTouch.UIKit.UILabel __mt__duration;
		
		private MonoTouch.UIKit.UISlider __mt__volumeSlider;
		
		private MonoTouch.UIKit.UISlider __mt__progressBar;
		
		private MonoTouch.UIKit.UILabel __mt__fileName;
		
		private CALevelMeter __mt__lvlMeter_in;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Export("volumeSliderMoved:")]
		partial void volumeSliderMoved (MonoTouch.UIKit.UISlider sender);

		[MonoTouch.Foundation.Export("progressSliderMoved:")]
		partial void progressSliderMoved (MonoTouch.UIKit.UISlider sender);

		[MonoTouch.Foundation.Export("playButtonPressed:")]
		partial void playButtonPressed (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Export("ffwButtonReleased:")]
		partial void ffwButtonReleased (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Export("rewButtonReleased:")]
		partial void rewButtonReleased (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Export("rewButtonPressed:")]
		partial void rewButtonPressed (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Export("ffwButtonPressed:")]
		partial void ffwButtonPressed (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Connect("_playButton")]
		private MonoTouch.UIKit.UIButton _playButton {
			get {
				this.__mt__playButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("_playButton")));
				return this.__mt__playButton;
			}
			set {
				this.__mt__playButton = value;
				this.SetNativeField("_playButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("_rewButton")]
		private MonoTouch.UIKit.UIButton _rewButton {
			get {
				this.__mt__rewButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("_rewButton")));
				return this.__mt__rewButton;
			}
			set {
				this.__mt__rewButton = value;
				this.SetNativeField("_rewButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("_ffwButton")]
		private MonoTouch.UIKit.UIButton _ffwButton {
			get {
				this.__mt__ffwButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("_ffwButton")));
				return this.__mt__ffwButton;
			}
			set {
				this.__mt__ffwButton = value;
				this.SetNativeField("_ffwButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("_currentTime")]
		private MonoTouch.UIKit.UILabel _currentTime {
			get {
				this.__mt__currentTime = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("_currentTime")));
				return this.__mt__currentTime;
			}
			set {
				this.__mt__currentTime = value;
				this.SetNativeField("_currentTime", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("_duration")]
		private MonoTouch.UIKit.UILabel _duration {
			get {
				this.__mt__duration = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("_duration")));
				return this.__mt__duration;
			}
			set {
				this.__mt__duration = value;
				this.SetNativeField("_duration", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("_volumeSlider")]
		private MonoTouch.UIKit.UISlider _volumeSlider {
			get {
				this.__mt__volumeSlider = ((MonoTouch.UIKit.UISlider)(this.GetNativeField("_volumeSlider")));
				return this.__mt__volumeSlider;
			}
			set {
				this.__mt__volumeSlider = value;
				this.SetNativeField("_volumeSlider", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("_progressBar")]
		private MonoTouch.UIKit.UISlider _progressBar {
			get {
				this.__mt__progressBar = ((MonoTouch.UIKit.UISlider)(this.GetNativeField("_progressBar")));
				return this.__mt__progressBar;
			}
			set {
				this.__mt__progressBar = value;
				this.SetNativeField("_progressBar", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("_fileName")]
		private MonoTouch.UIKit.UILabel _fileName {
			get {
				this.__mt__fileName = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("_fileName")));
				return this.__mt__fileName;
			}
			set {
				this.__mt__fileName = value;
				this.SetNativeField("_fileName", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("_lvlMeter_in")]
		private CALevelMeter _lvlMeter_in {
			get {
				this.__mt__lvlMeter_in = ((CALevelMeter)(this.GetNativeField("_lvlMeter_in")));
				return this.__mt__lvlMeter_in;
			}
			set {
				this.__mt__lvlMeter_in = value;
				this.SetNativeField("_lvlMeter_in", value);
			}
		}
	}
	
	// Base type probably should be MonoTouch.UIKit.UIView or subclass
	[MonoTouch.Foundation.Register("CALevelMeter")]
	public partial class CALevelMeter {
	}
}
