// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_Drawing.Screens.iPad.Home {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("HomeScreen")]
	public partial class HomeScreen {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_btnDrawRectVsPath;
		
		private MonoTouch.UIKit.UIButton __mt_btnDrawUsingCGBitmapContext;
		
		private MonoTouch.UIKit.UIButton __mt_btnDrawUsingLayers;
		
		private MonoTouch.UIKit.UIButton __mt_btnOffScreenCoords;
		
		private MonoTouch.UIKit.UIButton __mt_btnOnScreenCoords;
		
		private MonoTouch.UIKit.UIButton __mt_btnOnScreenUncorrectedText;
		
		private MonoTouch.UIKit.UIButton __mt_btnOffScreenFlag;
		
		private MonoTouch.UIKit.UIButton __mt_btnImage;
		
		private MonoTouch.UIKit.UIButton __mt_btnPatterns;
		
		private MonoTouch.UIKit.UIButton __mt_btnStencilPattern;
		
		private MonoTouch.UIKit.UIButton __mt_btnShadows;
		
		private MonoTouch.UIKit.UIButton __mt_btnHitTesting;
		
		private MonoTouch.UIKit.UIButton __mt_btnTouchDrawing;
		
		private MonoTouch.UIKit.UIButton __mt_btnOnScreenFlag;
		
		private MonoTouch.UIKit.UIButton __mt_btnTransformations;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnDrawRectVsPath")]
		private MonoTouch.UIKit.UIButton btnDrawRectVsPath {
			get {
				this.__mt_btnDrawRectVsPath = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnDrawRectVsPath")));
				return this.__mt_btnDrawRectVsPath;
			}
			set {
				this.__mt_btnDrawRectVsPath = value;
				this.SetNativeField("btnDrawRectVsPath", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnDrawUsingCGBitmapContext")]
		private MonoTouch.UIKit.UIButton btnDrawUsingCGBitmapContext {
			get {
				this.__mt_btnDrawUsingCGBitmapContext = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnDrawUsingCGBitmapContext")));
				return this.__mt_btnDrawUsingCGBitmapContext;
			}
			set {
				this.__mt_btnDrawUsingCGBitmapContext = value;
				this.SetNativeField("btnDrawUsingCGBitmapContext", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnDrawUsingLayers")]
		private MonoTouch.UIKit.UIButton btnDrawUsingLayers {
			get {
				this.__mt_btnDrawUsingLayers = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnDrawUsingLayers")));
				return this.__mt_btnDrawUsingLayers;
			}
			set {
				this.__mt_btnDrawUsingLayers = value;
				this.SetNativeField("btnDrawUsingLayers", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnOffScreenCoords")]
		private MonoTouch.UIKit.UIButton btnOffScreenCoords {
			get {
				this.__mt_btnOffScreenCoords = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnOffScreenCoords")));
				return this.__mt_btnOffScreenCoords;
			}
			set {
				this.__mt_btnOffScreenCoords = value;
				this.SetNativeField("btnOffScreenCoords", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnOnScreenCoords")]
		private MonoTouch.UIKit.UIButton btnOnScreenCoords {
			get {
				this.__mt_btnOnScreenCoords = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnOnScreenCoords")));
				return this.__mt_btnOnScreenCoords;
			}
			set {
				this.__mt_btnOnScreenCoords = value;
				this.SetNativeField("btnOnScreenCoords", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnOnScreenUncorrectedText")]
		private MonoTouch.UIKit.UIButton btnOnScreenUncorrectedText {
			get {
				this.__mt_btnOnScreenUncorrectedText = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnOnScreenUncorrectedText")));
				return this.__mt_btnOnScreenUncorrectedText;
			}
			set {
				this.__mt_btnOnScreenUncorrectedText = value;
				this.SetNativeField("btnOnScreenUncorrectedText", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnOffScreenFlag")]
		private MonoTouch.UIKit.UIButton btnOffScreenFlag {
			get {
				this.__mt_btnOffScreenFlag = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnOffScreenFlag")));
				return this.__mt_btnOffScreenFlag;
			}
			set {
				this.__mt_btnOffScreenFlag = value;
				this.SetNativeField("btnOffScreenFlag", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnImage")]
		private MonoTouch.UIKit.UIButton btnImage {
			get {
				this.__mt_btnImage = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnImage")));
				return this.__mt_btnImage;
			}
			set {
				this.__mt_btnImage = value;
				this.SetNativeField("btnImage", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnPatterns")]
		private MonoTouch.UIKit.UIButton btnPatterns {
			get {
				this.__mt_btnPatterns = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnPatterns")));
				return this.__mt_btnPatterns;
			}
			set {
				this.__mt_btnPatterns = value;
				this.SetNativeField("btnPatterns", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnStencilPattern")]
		private MonoTouch.UIKit.UIButton btnStencilPattern {
			get {
				this.__mt_btnStencilPattern = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnStencilPattern")));
				return this.__mt_btnStencilPattern;
			}
			set {
				this.__mt_btnStencilPattern = value;
				this.SetNativeField("btnStencilPattern", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnShadows")]
		private MonoTouch.UIKit.UIButton btnShadows {
			get {
				this.__mt_btnShadows = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnShadows")));
				return this.__mt_btnShadows;
			}
			set {
				this.__mt_btnShadows = value;
				this.SetNativeField("btnShadows", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnHitTesting")]
		private MonoTouch.UIKit.UIButton btnHitTesting {
			get {
				this.__mt_btnHitTesting = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnHitTesting")));
				return this.__mt_btnHitTesting;
			}
			set {
				this.__mt_btnHitTesting = value;
				this.SetNativeField("btnHitTesting", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnTouchDrawing")]
		private MonoTouch.UIKit.UIButton btnTouchDrawing {
			get {
				this.__mt_btnTouchDrawing = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnTouchDrawing")));
				return this.__mt_btnTouchDrawing;
			}
			set {
				this.__mt_btnTouchDrawing = value;
				this.SetNativeField("btnTouchDrawing", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnOnScreenFlag")]
		private MonoTouch.UIKit.UIButton btnOnScreenFlag {
			get {
				this.__mt_btnOnScreenFlag = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnOnScreenFlag")));
				return this.__mt_btnOnScreenFlag;
			}
			set {
				this.__mt_btnOnScreenFlag = value;
				this.SetNativeField("btnOnScreenFlag", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnTransformations")]
		private MonoTouch.UIKit.UIButton btnTransformations {
			get {
				this.__mt_btnTransformations = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnTransformations")));
				return this.__mt_btnTransformations;
			}
			set {
				this.__mt_btnTransformations = value;
				this.SetNativeField("btnTransformations", value);
			}
		}
	}
}
