// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace reachability {
	
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("ReachabilityAppDelegate")]
	public partial class ReachabilityAppDelegate {
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("window")]
		private MonoTouch.UIKit.UIWindow window {
			get {
				return ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
			}
			set {
				this.SetNativeField("window", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("contentView")]
		private MonoTouch.UIKit.UIView contentView {
			get {
				return ((MonoTouch.UIKit.UIView)(this.GetNativeField("contentView")));
			}
			set {
				this.SetNativeField("contentView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("summaryLabel")]
		private MonoTouch.UIKit.UILabel summaryLabel {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("summaryLabel")));
			}
			set {
				this.SetNativeField("summaryLabel", value);
			}
		}
	}
}
