// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoCatalog {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("ImagesViewController")]
	public partial class ImagesViewController {
		
		[MonoTouch.Foundation.Export("sliderAction:")]partial void sliderAction (MonoTouch.UIKit.UISlider sender);

		[MonoTouch.Foundation.Connect("view")]
		protected MonoTouch.UIKit.UIView view {
			get {
				return ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
			}
			set {
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imageView")]
		protected MonoTouch.UIKit.UIImageView imageView {
			get {
				return ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imageView")));
			}
			set {
				this.SetNativeField("imageView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("slider")]
		protected MonoTouch.UIKit.UISlider slider {
			get {
				return ((MonoTouch.UIKit.UISlider)(this.GetNativeField("slider")));
			}
			set {
				this.SetNativeField("slider", value);
			}
		}
	}
}
