// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoCatalog {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("PickerViewController")]
	public partial class PickerViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UISegmentedControl __mt_buttonBarSegmentedControl;
		
		private MonoTouch.UIKit.UISegmentedControl __mt_pickerStyleSegmentedControl;
		
		private MonoTouch.UIKit.UILabel __mt_segmentLabel;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Export("togglePickerStyle:")]
		partial void togglePickerStyle (MonoTouch.UIKit.UISegmentedControl sender);

		[MonoTouch.Foundation.Export("togglePickers:")]
		partial void togglePickers (MonoTouch.UIKit.UIBarButtonItem sender);

		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("buttonBarSegmentedControl")]
		private MonoTouch.UIKit.UISegmentedControl buttonBarSegmentedControl {
			get {
				this.__mt_buttonBarSegmentedControl = ((MonoTouch.UIKit.UISegmentedControl)(this.GetNativeField("buttonBarSegmentedControl")));
				return this.__mt_buttonBarSegmentedControl;
			}
			set {
				this.__mt_buttonBarSegmentedControl = value;
				this.SetNativeField("buttonBarSegmentedControl", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("pickerStyleSegmentedControl")]
		private MonoTouch.UIKit.UISegmentedControl pickerStyleSegmentedControl {
			get {
				this.__mt_pickerStyleSegmentedControl = ((MonoTouch.UIKit.UISegmentedControl)(this.GetNativeField("pickerStyleSegmentedControl")));
				return this.__mt_pickerStyleSegmentedControl;
			}
			set {
				this.__mt_pickerStyleSegmentedControl = value;
				this.SetNativeField("pickerStyleSegmentedControl", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("segmentLabel")]
		private MonoTouch.UIKit.UILabel segmentLabel {
			get {
				this.__mt_segmentLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("segmentLabel")));
				return this.__mt_segmentLabel;
			}
			set {
				this.__mt_segmentLabel = value;
				this.SetNativeField("segmentLabel", value);
			}
		}
	}
}
