// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_SplitView.Screens.DetailView {
	
	
	// Base type probably should be UIKit.UIViewController or subclass
	[Foundation.Register("DetailViewScreen")]
	public partial class DetailViewScreen {
		
		private UIKit.UIView __mt_view;
		
		private UIKit.UILabel __mt_lblItemNumber;
		
		private UIKit.UIToolbar __mt_tlbrTop;
		
		#pragma warning disable 0169
		[Foundation.Connect("view")]
		private UIKit.UIView view {
			get {
				this.__mt_view = ((UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[Foundation.Connect("lblItemNumber")]
		private UIKit.UILabel lblItemNumber {
			get {
				this.__mt_lblItemNumber = ((UIKit.UILabel)(this.GetNativeField("lblItemNumber")));
				return this.__mt_lblItemNumber;
			}
			set {
				this.__mt_lblItemNumber = value;
				this.SetNativeField("lblItemNumber", value);
			}
		}
		
		[Foundation.Connect("tlbrTop")]
		private UIKit.UIToolbar tlbrTop {
			get {
				this.__mt_tlbrTop = ((UIKit.UIToolbar)(this.GetNativeField("tlbrTop")));
				return this.__mt_tlbrTop;
			}
			set {
				this.__mt_tlbrTop = value;
				this.SetNativeField("tlbrTop", value);
			}
		}
	}
}
