// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CloudKitAtlas
{
	public partial class LoadingViewController : UIViewController
	{
		public LoadingViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
