// This file has been autogenerated from a class added in the UI designer.

using System;
using CloudKit;
using Foundation;
using UIKit;

namespace CloudKitAtlas
{
	public partial class NavigationBar : UINavigationBar
	{
		public NavigationBar (IntPtr handle) : base (handle)
		{
		}

		internal void ShowNotificationAlert (CKNotification notification)
		{
			throw new NotImplementedException ();
		}
	}
}
