// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_SharedResources.Screens.iPhone.Network {
	
	
	// Base type probably should be UIKit.UIViewController or subclass
	[Foundation.Register("ActivityIndicatorScreen")]
	public partial class ActivityIndicatorScreen {
		
		private UIKit.UIView __mt_view;
		
		private UIKit.UISwitch __mt_swtchActivityIndicator1;
		
		private UIKit.UISwitch __mt_swtchActivityIndicator2;
		
		#pragma warning disable 0169
		[Foundation.Connect("view")]
		private UIKit.UIView view {
			get {
				this.__mt_view = ((UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[Foundation.Connect("swtchActivityIndicator1")]
		private UIKit.UISwitch swtchActivityIndicator1 {
			get {
				this.__mt_swtchActivityIndicator1 = ((UIKit.UISwitch)(this.GetNativeField("swtchActivityIndicator1")));
				return this.__mt_swtchActivityIndicator1;
			}
			set {
				this.__mt_swtchActivityIndicator1 = value;
				this.SetNativeField("swtchActivityIndicator1", value);
			}
		}
		
		[Foundation.Connect("swtchActivityIndicator2")]
		private UIKit.UISwitch swtchActivityIndicator2 {
			get {
				this.__mt_swtchActivityIndicator2 = ((UIKit.UISwitch)(this.GetNativeField("swtchActivityIndicator2")));
				return this.__mt_swtchActivityIndicator2;
			}
			set {
				this.__mt_swtchActivityIndicator2 = value;
				this.SetNativeField("swtchActivityIndicator2", value);
			}
		}
	}
}
