// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_Touch.Screens.iPhone.Home {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[Foundation.Register("Home_iPhone")]
	public partial class Home_iPhone {
		
		private UIKit.UIView __mt_view;
		
		private UIKit.UIButton __mt_btnGestureRecognizers;
		
		private UIKit.UIButton __mt_btnTouch;
		
		private UIKit.UIButton __mt_btnCustomGestureRecognizer;
		
		#pragma warning disable 0169
		[Foundation.Connect("view")]
		private UIKit.UIView view {
			get {
				this.__mt_view = ((UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[Foundation.Connect("btnGestureRecognizers")]
		private UIKit.UIButton btnGestureRecognizers {
			get {
				this.__mt_btnGestureRecognizers = ((UIKit.UIButton)(this.GetNativeField("btnGestureRecognizers")));
				return this.__mt_btnGestureRecognizers;
			}
			set {
				this.__mt_btnGestureRecognizers = value;
				this.SetNativeField("btnGestureRecognizers", value);
			}
		}
		
		[Foundation.Connect("btnTouch")]
		private UIKit.UIButton btnTouch {
			get {
				this.__mt_btnTouch = ((UIKit.UIButton)(this.GetNativeField("btnTouch")));
				return this.__mt_btnTouch;
			}
			set {
				this.__mt_btnTouch = value;
				this.SetNativeField("btnTouch", value);
			}
		}
		
		[Foundation.Connect("btnCustomGestureRecognizer")]
		private UIKit.UIButton btnCustomGestureRecognizer {
			get {
				this.__mt_btnCustomGestureRecognizer = ((UIKit.UIButton)(this.GetNativeField("btnCustomGestureRecognizer")));
				return this.__mt_btnCustomGestureRecognizer;
			}
			set {
				this.__mt_btnCustomGestureRecognizer = value;
				this.SetNativeField("btnCustomGestureRecognizer", value);
			}
		}
	}
}
