// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ZoomingPdfViewer
{
	public partial class DataViewController : UIViewController
	{
		public DataViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
