// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using System.Collections.Generic;

namespace TableSearch
{
	public class ResultsTableController : BaseTableViewController
	{
		public List<Product> FilteredProducts { get; set; }

		public override nint RowsInSection (UITableView tableview, nint section)
		{
			return FilteredProducts.Count;
		}

		public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
		{
			Product product = FilteredProducts [indexPath.Row];
			UITableViewCell cell = tableView.DequeueReusableCell (cellIdentifier);
			ConfigureCell (cell, product);
			return cell;
		}
	}
}
