// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AUSoundTriggeredPlayingSoundMemoryBased {
	
	
	// Base type probably should be UIKit.UIViewController or subclass
	[Foundation.Register("MainView")]
	public partial class MainView {
		
		private UIKit.UIView __mt_view;
		
		private UIKit.UIButton __mt__playButton;
		
		private UIKit.UIButton __mt__stopButton;
		
		private UIKit.UISlider __mt__slider;
		
		private UIKit.UILabel __mt__signalLevelLabel;
		
		#pragma warning disable 0169
		[Foundation.Connect("view")]
		private UIKit.UIView view {
			get {
				this.__mt_view = ((UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[Foundation.Connect("_playButton")]
		private UIKit.UIButton _playButton {
			get {
				this.__mt__playButton = ((UIKit.UIButton)(this.GetNativeField("_playButton")));
				return this.__mt__playButton;
			}
			set {
				this.__mt__playButton = value;
				this.SetNativeField("_playButton", value);
			}
		}
		
		[Foundation.Connect("_stopButton")]
		private UIKit.UIButton _stopButton {
			get {
				this.__mt__stopButton = ((UIKit.UIButton)(this.GetNativeField("_stopButton")));
				return this.__mt__stopButton;
			}
			set {
				this.__mt__stopButton = value;
				this.SetNativeField("_stopButton", value);
			}
		}
		
		[Foundation.Connect("_slider")]
		private UIKit.UISlider _slider {
			get {
				this.__mt__slider = ((UIKit.UISlider)(this.GetNativeField("_slider")));
				return this.__mt__slider;
			}
			set {
				this.__mt__slider = value;
				this.SetNativeField("_slider", value);
			}
		}
		
		[Foundation.Connect("_signalLevelLabel")]
		private UIKit.UILabel _signalLevelLabel {
			get {
				this.__mt__signalLevelLabel = ((UIKit.UILabel)(this.GetNativeField("_signalLevelLabel")));
				return this.__mt__signalLevelLabel;
			}
			set {
				this.__mt__signalLevelLabel = value;
				this.SetNativeField("_signalLevelLabel", value);
			}
		}
	}
}
