// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_ContentControls.Screens.iPhone.Maps {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("MapsHome")]
	public partial class MapsHome {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_btnBasicMap;
		
		private MonoTouch.UIKit.UIButton __mt_btnMapWithOverlay;
		
		private MonoTouch.UIKit.UIButton __mt_btnMapWithAnnotations;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnBasicMap")]
		private MonoTouch.UIKit.UIButton btnBasicMap {
			get {
				this.__mt_btnBasicMap = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnBasicMap")));
				return this.__mt_btnBasicMap;
			}
			set {
				this.__mt_btnBasicMap = value;
				this.SetNativeField("btnBasicMap", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnMapWithOverlay")]
		private MonoTouch.UIKit.UIButton btnMapWithOverlay {
			get {
				this.__mt_btnMapWithOverlay = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnMapWithOverlay")));
				return this.__mt_btnMapWithOverlay;
			}
			set {
				this.__mt_btnMapWithOverlay = value;
				this.SetNativeField("btnMapWithOverlay", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnMapWithAnnotations")]
		private MonoTouch.UIKit.UIButton btnMapWithAnnotations {
			get {
				this.__mt_btnMapWithAnnotations = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnMapWithAnnotations")));
				return this.__mt_btnMapWithAnnotations;
			}
			set {
				this.__mt_btnMapWithAnnotations = value;
				this.SetNativeField("btnMapWithAnnotations", value);
			}
		}
	}
}
