// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
[MonoTouch.Foundation.Register("ImagesViewController")]
public partial class ImagesViewController {
	
	#pragma warning disable 0169
	[MonoTouch.Foundation.Export("sliderAction:")]
	partial void sliderAction (MonoTouch.UIKit.UISlider sender);

	[MonoTouch.Foundation.Connect("view")]
	private MonoTouch.UIKit.UIView view {
		get {
			return ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
		}
		set {
			this.SetNativeField("view", value);
		}
	}
	
	[MonoTouch.Foundation.Connect("imageView")]
	private MonoTouch.UIKit.UIImageView imageView {
		get {
			return ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imageView")));
		}
		set {
			this.SetNativeField("imageView", value);
		}
	}
	
	[MonoTouch.Foundation.Connect("slider")]
	private MonoTouch.UIKit.UISlider slider {
		get {
			return ((MonoTouch.UIKit.UISlider)(this.GetNativeField("slider")));
		}
		set {
			this.SetNativeField("slider", value);
		}
	}
}
