// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_ContentControls.Screens.iPhone.Browsers {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("BrowsersHome")]
	public partial class BrowsersHome {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_btnLocalBrowser;
		
		private MonoTouch.UIKit.UIButton __mt_btnWebBrowser;
		
		private MonoTouch.UIKit.UIButton __mt_btnInteractivity;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnLocalBrowser")]
		private MonoTouch.UIKit.UIButton btnLocalBrowser {
			get {
				this.__mt_btnLocalBrowser = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnLocalBrowser")));
				return this.__mt_btnLocalBrowser;
			}
			set {
				this.__mt_btnLocalBrowser = value;
				this.SetNativeField("btnLocalBrowser", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnWebBrowser")]
		private MonoTouch.UIKit.UIButton btnWebBrowser {
			get {
				this.__mt_btnWebBrowser = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnWebBrowser")));
				return this.__mt_btnWebBrowser;
			}
			set {
				this.__mt_btnWebBrowser = value;
				this.SetNativeField("btnWebBrowser", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnInteractivity")]
		private MonoTouch.UIKit.UIButton btnInteractivity {
			get {
				this.__mt_btnInteractivity = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnInteractivity")));
				return this.__mt_btnInteractivity;
			}
			set {
				this.__mt_btnInteractivity = value;
				this.SetNativeField("btnInteractivity", value);
			}
		}
	}
}
