// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_CoreAnimation.Screens.iPad.ViewTransitions {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[Foundation.Register("BackTransitionViewController")]
	public partial class BackTransitionViewController {
		
		private UIKit.UIView _mt_view;
		
		private UIKit.UIButton _mt_btnBack;
		
		#pragma warning disable 0169
		[Foundation.Connect("view")]
		private UIKit.UIView view {
			get {
				 _mt_view = ((UIKit.UIView)(this.GetNativeField("view")));
				return  _mt_view;
			}
			set {
				 _mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[Foundation.Connect("btnBack")]
		private UIKit.UIButton btnBack {
			get {
				 _mt_btnBack = ((UIKit.UIButton)(this.GetNativeField("btnBack")));
				return  _mt_btnBack;
			}
			set {
				 _mt_btnBack = value;
				this.SetNativeField("btnBack", value);
			}
		}
	}
}
