// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.AVFoundation;
using MonoTouch.ObjCRuntime;

namespace AVCustomEdit
{
	public partial class PlayerView : UIView
	{
		public AVPlayer player 
		{
			get{
				return (this.Layer as AVPlayerLayer).Player;
			}
			set{
				(this.Layer as AVPlayerLayer).Player = value;
			}
		}

		public PlayerView (IntPtr handle) : base (handle)
		{
		}

		[Export ("layerClass")]
		public static Class LayerClass()
		{
			return new Class (typeof(AVPlayerLayer));
		}
	}
}
