// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace StreamingAudio {
	
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("AppDelegate")]
	public partial class AppDelegate {
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Export("startPlayback:")]
		partial void startPlayback (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Export("playControlClicked:")]
		partial void playControlClicked (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Export("volumeSet:")]
		partial void volumeSet (MonoTouch.UIKit.UISlider sender);

		[MonoTouch.Foundation.Connect("window")]
		private MonoTouch.UIKit.UIWindow window {
			get {
				return ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
			}
			set {
				this.SetNativeField("window", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("viewController")]
		private MonoTouch.UIKit.UINavigationController viewController {
			get {
				return ((MonoTouch.UIKit.UINavigationController)(this.GetNativeField("viewController")));
			}
			set {
				this.SetNativeField("viewController", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("entry")]
		private MonoTouch.UIKit.UITextField entry {
			get {
				return ((MonoTouch.UIKit.UITextField)(this.GetNativeField("entry")));
			}
			set {
				this.SetNativeField("entry", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("playController")]
		private MonoTouch.UIKit.UIViewController playController {
			get {
				return ((MonoTouch.UIKit.UIViewController)(this.GetNativeField("playController")));
			}
			set {
				this.SetNativeField("playController", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("volume")]
		private MonoTouch.UIKit.UISlider volume {
			get {
				return ((MonoTouch.UIKit.UISlider)(this.GetNativeField("volume")));
			}
			set {
				this.SetNativeField("volume", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("progress")]
		private MonoTouch.UIKit.UIProgressView progress {
			get {
				return ((MonoTouch.UIKit.UIProgressView)(this.GetNativeField("progress")));
			}
			set {
				this.SetNativeField("progress", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("status")]
		private MonoTouch.UIKit.UILabel status {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("status")));
			}
			set {
				this.SetNativeField("status", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("button")]
		private MonoTouch.UIKit.UIButton button {
			get {
				return ((MonoTouch.UIKit.UIButton)(this.GetNativeField("button")));
			}
			set {
				this.SetNativeField("button", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("playbackProgress")]
		private MonoTouch.UIKit.UIProgressView playbackProgress {
			get {
				return ((MonoTouch.UIKit.UIProgressView)(this.GetNativeField("playbackProgress")));
			}
			set {
				this.SetNativeField("playbackProgress", value);
			}
		}
	}
}
