// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WayUp {

	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[Foundation.Register("WhichWayIsUpAppDelegate")]
	public partial class WhichWayIsUpAppDelegate {

		private UIKit.UIWindow __mt_window;

		private CrateViewController __mt_crateViewController;

		#pragma warning disable 0169
		[Foundation.Connect("window")]
		private UIKit.UIWindow window {
			get {
				this.__mt_window = ((UIKit.UIWindow)(this.GetNativeField("window")));
				return this.__mt_window;
			}
			set {
				this.__mt_window = value;
				this.SetNativeField("window", value);
			}
		}

		[Foundation.Connect("crateViewController")]
		private CrateViewController crateViewController {
			get {
				this.__mt_crateViewController = ((CrateViewController)(this.GetNativeField("crateViewController")));
				return this.__mt_crateViewController;
			}
			set {
				this.__mt_crateViewController = value;
				this.SetNativeField("crateViewController", value);
			}
		}
	}

	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[Foundation.Register("CrateViewController")]
	public partial class CrateViewController {
	}
}
