// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoDevelopTouchCells {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("DetailViewController")]
	public partial class DetailViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIImageView __mt_checkedImage;
		
		private MonoTouch.UIKit.UILabel __mt_itemTitle;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("checkedImage")]
		private MonoTouch.UIKit.UIImageView checkedImage {
			get {
				this.__mt_checkedImage = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("checkedImage")));
				return this.__mt_checkedImage;
			}
			set {
				this.__mt_checkedImage = value;
				this.SetNativeField("checkedImage", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("itemTitle")]
		private MonoTouch.UIKit.UILabel itemTitle {
			get {
				this.__mt_itemTitle = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("itemTitle")));
				return this.__mt_itemTitle;
			}
			set {
				this.__mt_itemTitle = value;
				this.SetNativeField("itemTitle", value);
			}
		}
	}
}
