// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoDevelopTouchCells {
	
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("AppDelegate")]
	public partial class AppDelegate {
		
		[MonoTouch.Foundation.Connect("window")]
		protected MonoTouch.UIKit.UIWindow window {
			get {
				return ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
			}
			set {
				this.SetNativeField("window", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("myTableView")]
		protected MonoTouch.UIKit.UITableView myTableView {
			get {
				return ((MonoTouch.UIKit.UITableView)(this.GetNativeField("myTableView")));
			}
			set {
				this.SetNativeField("myTableView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("navigationController")]
		protected MonoTouch.UIKit.UINavigationController navigationController {
			get {
				return ((MonoTouch.UIKit.UINavigationController)(this.GetNativeField("navigationController")));
			}
			set {
				this.SetNativeField("navigationController", value);
			}
		}
	}
}
