// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_BackgroundExecution.Screens.iPhone {
	
	
	// Base type probably should be UIKit.UIViewController or subclass
	[Foundation.Register("HomeScreen_iPhone")]
	public partial class HomeScreen_iPhone {
		
		private UIKit.UIView __mt_view;
		
		private UIKit.UIButton __mt_btnStartLongRunningTask;
		
		#pragma warning disable 0169
		[Foundation.Connect("view")]
		private UIKit.UIView view {
			get {
				this.__mt_view = ((UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[Foundation.Connect("btnStartLongRunningTask")]
		private UIKit.UIButton btnStartLongRunningTask {
			get {
				this.__mt_btnStartLongRunningTask = ((UIKit.UIButton)(this.GetNativeField("btnStartLongRunningTask")));
				return this.__mt_btnStartLongRunningTask;
			}
			set {
				this.__mt_btnStartLongRunningTask = value;
				this.SetNativeField("btnStartLongRunningTask", value);
			}
		}
	}
}
