// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_SharedResources.Screens.iPhone.Contacts {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("AddressBookScreen")]
	public partial class AddressBookScreen {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_btnAddPhoneNumber;
		
		private MonoTouch.UIKit.UIButton __mt_btnSaveChanges;
		
		private MonoTouch.UIKit.UITableView __mt_tblPhoneNumbers;
		
		private MonoTouch.UIKit.UITextField __mt_txtFirstName;
		
		private MonoTouch.UIKit.UITextField __mt_txtLastName;
		
		private MonoTouch.UIKit.UITextField __mt_txtPhoneLabel;
		
		private MonoTouch.UIKit.UITextField __mt_txtPhoneNumber;
		
		private MonoTouch.UIKit.UIScrollView __mt_scrlMain;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnAddPhoneNumber")]
		private MonoTouch.UIKit.UIButton btnAddPhoneNumber {
			get {
				this.__mt_btnAddPhoneNumber = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnAddPhoneNumber")));
				return this.__mt_btnAddPhoneNumber;
			}
			set {
				this.__mt_btnAddPhoneNumber = value;
				this.SetNativeField("btnAddPhoneNumber", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnSaveChanges")]
		private MonoTouch.UIKit.UIButton btnSaveChanges {
			get {
				this.__mt_btnSaveChanges = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnSaveChanges")));
				return this.__mt_btnSaveChanges;
			}
			set {
				this.__mt_btnSaveChanges = value;
				this.SetNativeField("btnSaveChanges", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("tblPhoneNumbers")]
		private MonoTouch.UIKit.UITableView tblPhoneNumbers {
			get {
				this.__mt_tblPhoneNumbers = ((MonoTouch.UIKit.UITableView)(this.GetNativeField("tblPhoneNumbers")));
				return this.__mt_tblPhoneNumbers;
			}
			set {
				this.__mt_tblPhoneNumbers = value;
				this.SetNativeField("tblPhoneNumbers", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtFirstName")]
		private MonoTouch.UIKit.UITextField txtFirstName {
			get {
				this.__mt_txtFirstName = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtFirstName")));
				return this.__mt_txtFirstName;
			}
			set {
				this.__mt_txtFirstName = value;
				this.SetNativeField("txtFirstName", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtLastName")]
		private MonoTouch.UIKit.UITextField txtLastName {
			get {
				this.__mt_txtLastName = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtLastName")));
				return this.__mt_txtLastName;
			}
			set {
				this.__mt_txtLastName = value;
				this.SetNativeField("txtLastName", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtPhoneLabel")]
		private MonoTouch.UIKit.UITextField txtPhoneLabel {
			get {
				this.__mt_txtPhoneLabel = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtPhoneLabel")));
				return this.__mt_txtPhoneLabel;
			}
			set {
				this.__mt_txtPhoneLabel = value;
				this.SetNativeField("txtPhoneLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtPhoneNumber")]
		private MonoTouch.UIKit.UITextField txtPhoneNumber {
			get {
				this.__mt_txtPhoneNumber = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtPhoneNumber")));
				return this.__mt_txtPhoneNumber;
			}
			set {
				this.__mt_txtPhoneNumber = value;
				this.SetNativeField("txtPhoneNumber", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("scrlMain")]
		private MonoTouch.UIKit.UIScrollView scrlMain {
			get {
				this.__mt_scrlMain = ((MonoTouch.UIKit.UIScrollView)(this.GetNativeField("scrlMain")));
				return this.__mt_scrlMain;
			}
			set {
				this.__mt_scrlMain = value;
				this.SetNativeField("scrlMain", value);
			}
		}
	}
}
