// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_SharedResources.Screens.iPhone.Contacts {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("ContactPickerScreen")]
	public partial class ContactPickerScreen {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_btnChooseContact;
		
		private MonoTouch.UIKit.UILabel __mt_lblFirstName;
		
		private MonoTouch.UIKit.UILabel __mt_lblLastName;
		
		private MonoTouch.UIKit.UIButton __mt_btnViewSelectedContact;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnChooseContact")]
		private MonoTouch.UIKit.UIButton btnChooseContact {
			get {
				this.__mt_btnChooseContact = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnChooseContact")));
				return this.__mt_btnChooseContact;
			}
			set {
				this.__mt_btnChooseContact = value;
				this.SetNativeField("btnChooseContact", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblFirstName")]
		private MonoTouch.UIKit.UILabel lblFirstName {
			get {
				this.__mt_lblFirstName = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lblFirstName")));
				return this.__mt_lblFirstName;
			}
			set {
				this.__mt_lblFirstName = value;
				this.SetNativeField("lblFirstName", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblLastName")]
		private MonoTouch.UIKit.UILabel lblLastName {
			get {
				this.__mt_lblLastName = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lblLastName")));
				return this.__mt_lblLastName;
			}
			set {
				this.__mt_lblLastName = value;
				this.SetNativeField("lblLastName", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnViewSelectedContact")]
		private MonoTouch.UIKit.UIButton btnViewSelectedContact {
			get {
				this.__mt_btnViewSelectedContact = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnViewSelectedContact")));
				return this.__mt_btnViewSelectedContact;
			}
			set {
				this.__mt_btnViewSelectedContact = value;
				this.SetNativeField("btnViewSelectedContact", value);
			}
		}
	}
}
