// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_SharedResources.Screens.iPhone.Contacts {
	
	
	// Base type probably should be UIKit.UIViewController or subclass
	[Foundation.Register("NewAndUnknownContactScreen")]
	public partial class NewAndUnknownContactScreen {
		
		private UIKit.UIView __mt_view;
		
		private UIKit.UIButton __mt_btnCreateNewContact;
		
		private UIKit.UIButton __mt_btnPromptForUnknown;
		
		private UIKit.UITextField __mt_txtFirstName;
		
		private UIKit.UITextField __mt_txtLastName;
		
		#pragma warning disable 0169
		[Foundation.Connect("view")]
		private UIKit.UIView view {
			get {
				this.__mt_view = ((UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[Foundation.Connect("btnCreateNewContact")]
		private UIKit.UIButton btnCreateNewContact {
			get {
				this.__mt_btnCreateNewContact = ((UIKit.UIButton)(this.GetNativeField("btnCreateNewContact")));
				return this.__mt_btnCreateNewContact;
			}
			set {
				this.__mt_btnCreateNewContact = value;
				this.SetNativeField("btnCreateNewContact", value);
			}
		}
		
		[Foundation.Connect("btnPromptForUnknown")]
		private UIKit.UIButton btnPromptForUnknown {
			get {
				this.__mt_btnPromptForUnknown = ((UIKit.UIButton)(this.GetNativeField("btnPromptForUnknown")));
				return this.__mt_btnPromptForUnknown;
			}
			set {
				this.__mt_btnPromptForUnknown = value;
				this.SetNativeField("btnPromptForUnknown", value);
			}
		}
		
		[Foundation.Connect("txtFirstName")]
		private UIKit.UITextField txtFirstName {
			get {
				this.__mt_txtFirstName = ((UIKit.UITextField)(this.GetNativeField("txtFirstName")));
				return this.__mt_txtFirstName;
			}
			set {
				this.__mt_txtFirstName = value;
				this.SetNativeField("txtFirstName", value);
			}
		}
		
		[Foundation.Connect("txtLastName")]
		private UIKit.UITextField txtLastName {
			get {
				this.__mt_txtLastName = ((UIKit.UITextField)(this.GetNativeField("txtLastName")));
				return this.__mt_txtLastName;
			}
			set {
				this.__mt_txtLastName = value;
				this.SetNativeField("txtLastName", value);
			}
		}
	}
}
