// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoCatalog {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("AddressBookController")]
	public partial class AddressBookController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UILabel __mt_firstName;
		
		private MonoTouch.UIKit.UILabel __mt_lastName;
		
		private MonoTouch.UIKit.UISwitch __mt_performAction;
		
		private MonoTouch.UIKit.UISwitch __mt_selectProperty;
		
		private MonoTouch.UIKit.UILabel __mt_property;
		
		private MonoTouch.UIKit.UILabel __mt_identifier;
		
		private MonoTouch.UIKit.UILabel __mt_toString;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Export("showPicker:")]
		partial void showPicker (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("firstName")]
		private MonoTouch.UIKit.UILabel firstName {
			get {
				this.__mt_firstName = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("firstName")));
				return this.__mt_firstName;
			}
			set {
				this.__mt_firstName = value;
				this.SetNativeField("firstName", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lastName")]
		private MonoTouch.UIKit.UILabel lastName {
			get {
				this.__mt_lastName = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lastName")));
				return this.__mt_lastName;
			}
			set {
				this.__mt_lastName = value;
				this.SetNativeField("lastName", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("performAction")]
		private MonoTouch.UIKit.UISwitch performAction {
			get {
				this.__mt_performAction = ((MonoTouch.UIKit.UISwitch)(this.GetNativeField("performAction")));
				return this.__mt_performAction;
			}
			set {
				this.__mt_performAction = value;
				this.SetNativeField("performAction", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("selectProperty")]
		private MonoTouch.UIKit.UISwitch selectProperty {
			get {
				this.__mt_selectProperty = ((MonoTouch.UIKit.UISwitch)(this.GetNativeField("selectProperty")));
				return this.__mt_selectProperty;
			}
			set {
				this.__mt_selectProperty = value;
				this.SetNativeField("selectProperty", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("property")]
		private MonoTouch.UIKit.UILabel property {
			get {
				this.__mt_property = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("property")));
				return this.__mt_property;
			}
			set {
				this.__mt_property = value;
				this.SetNativeField("property", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("identifier")]
		private MonoTouch.UIKit.UILabel identifier {
			get {
				this.__mt_identifier = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("identifier")));
				return this.__mt_identifier;
			}
			set {
				this.__mt_identifier = value;
				this.SetNativeField("identifier", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("toString")]
		private MonoTouch.UIKit.UILabel toString {
			get {
				this.__mt_toString = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("toString")));
				return this.__mt_toString;
			}
			set {
				this.__mt_toString = value;
				this.SetNativeField("toString", value);
			}
		}
	}
}
