// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoCatalog {
	
	
	// Base type probably should be UIKit.UIViewController or subclass
	[Foundation.Register("ButtonsViewController")]
	public partial class ButtonsViewController {
		
		private UIKit.UITableView __mt_view;
		
		#pragma warning disable 0169
		[Foundation.Connect("view")]
		private UIKit.UITableView view {
			get {
				this.__mt_view = ((UIKit.UITableView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
	}
}
