// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoCatalog {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("ImagesViewController")]
	public partial class ImagesViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIImageView __mt_imageView;
		
		private MonoTouch.UIKit.UISlider __mt_slider;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Export("sliderAction:")]
		partial void sliderAction (MonoTouch.UIKit.UISlider sender);

		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imageView")]
		private MonoTouch.UIKit.UIImageView imageView {
			get {
				this.__mt_imageView = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imageView")));
				return this.__mt_imageView;
			}
			set {
				this.__mt_imageView = value;
				this.SetNativeField("imageView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("slider")]
		private MonoTouch.UIKit.UISlider slider {
			get {
				this.__mt_slider = ((MonoTouch.UIKit.UISlider)(this.GetNativeField("slider")));
				return this.__mt_slider;
			}
			set {
				this.__mt_slider = value;
				this.SetNativeField("slider", value);
			}
		}
	}
}
