// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoCatalog {
	
	
	// Base type probably should be UIKit.UIViewController or subclass
	[Foundation.Register("ImagesViewController")]
	public partial class ImagesViewController {
		
		private UIKit.UIView __mt_view;
		
		private UIKit.UIImageView __mt_imageView;
		
		private UIKit.UISlider __mt_slider;
		
		#pragma warning disable 0169
		[Foundation.Export("sliderAction:")]
		partial void sliderAction (UIKit.UISlider sender);

		[Foundation.Connect("view")]
		private UIKit.UIView view {
			get {
				this.__mt_view = ((UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[Foundation.Connect("imageView")]
		private UIKit.UIImageView imageView {
			get {
				this.__mt_imageView = ((UIKit.UIImageView)(this.GetNativeField("imageView")));
				return this.__mt_imageView;
			}
			set {
				this.__mt_imageView = value;
				this.SetNativeField("imageView", value);
			}
		}
		
		[Foundation.Connect("slider")]
		private UIKit.UISlider slider {
			get {
				this.__mt_slider = ((UIKit.UISlider)(this.GetNativeField("slider")));
				return this.__mt_slider;
			}
			set {
				this.__mt_slider = value;
				this.SetNativeField("slider", value);
			}
		}
	}
}
