// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_Touch.Screens.iPhone.SimpleTouch {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("Touches_iPhone")]
	public partial class Touches_iPhone {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIImageView __mt_imgDragMe;
		
		private MonoTouch.UIKit.UIImageView __mt_imgTouchMe;
		
		private MonoTouch.UIKit.UILabel __mt_lblTouchStatus;
		
		private MonoTouch.UIKit.UIImageView __mt_imgTapMe;
		
		private MonoTouch.UIKit.UILabel __mt_lblNumberOfFingers;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imgDragMe")]
		private MonoTouch.UIKit.UIImageView imgDragMe {
			get {
				this.__mt_imgDragMe = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imgDragMe")));
				return this.__mt_imgDragMe;
			}
			set {
				this.__mt_imgDragMe = value;
				this.SetNativeField("imgDragMe", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imgTouchMe")]
		private MonoTouch.UIKit.UIImageView imgTouchMe {
			get {
				this.__mt_imgTouchMe = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imgTouchMe")));
				return this.__mt_imgTouchMe;
			}
			set {
				this.__mt_imgTouchMe = value;
				this.SetNativeField("imgTouchMe", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblTouchStatus")]
		private MonoTouch.UIKit.UILabel lblTouchStatus {
			get {
				this.__mt_lblTouchStatus = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lblTouchStatus")));
				return this.__mt_lblTouchStatus;
			}
			set {
				this.__mt_lblTouchStatus = value;
				this.SetNativeField("lblTouchStatus", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imgTapMe")]
		private MonoTouch.UIKit.UIImageView imgTapMe {
			get {
				this.__mt_imgTapMe = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imgTapMe")));
				return this.__mt_imgTapMe;
			}
			set {
				this.__mt_imgTapMe = value;
				this.SetNativeField("imgTapMe", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblNumberOfFingers")]
		private MonoTouch.UIKit.UILabel lblNumberOfFingers {
			get {
				this.__mt_lblNumberOfFingers = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lblNumberOfFingers")));
				return this.__mt_lblNumberOfFingers;
			}
			set {
				this.__mt_lblNumberOfFingers = value;
				this.SetNativeField("lblNumberOfFingers", value);
			}
		}
	}
}
