// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoDevelopTouchCells {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("DetailViewController")]
	public partial class DetailViewController {
		
		[MonoTouch.Foundation.Connect("view")]
		protected MonoTouch.UIKit.UIView view {
			get {
				return ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
			}
			set {
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("checkedImage")]
		protected MonoTouch.UIKit.UIImageView checkedImage {
			get {
				return ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("checkedImage")));
			}
			set {
				this.SetNativeField("checkedImage", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("itemTitle")]
		protected MonoTouch.UIKit.UILabel itemTitle {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("itemTitle")));
			}
			set {
				this.SetNativeField("itemTitle", value);
			}
		}
	}
}
