// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_SharedResources.Screens.iPhone.Accelerometer {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("XYZDataScreen")]
	public partial class XYZDataScreen {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UILabel __mt_lblX;
		
		private MonoTouch.UIKit.UILabel __mt_lblY;
		
		private MonoTouch.UIKit.UILabel __mt_lblZ;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblX")]
		private MonoTouch.UIKit.UILabel lblX {
			get {
				this.__mt_lblX = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lblX")));
				return this.__mt_lblX;
			}
			set {
				this.__mt_lblX = value;
				this.SetNativeField("lblX", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblY")]
		private MonoTouch.UIKit.UILabel lblY {
			get {
				this.__mt_lblY = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lblY")));
				return this.__mt_lblY;
			}
			set {
				this.__mt_lblY = value;
				this.SetNativeField("lblY", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblZ")]
		private MonoTouch.UIKit.UILabel lblZ {
			get {
				this.__mt_lblZ = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lblZ")));
				return this.__mt_lblZ;
			}
			set {
				this.__mt_lblZ = value;
				this.SetNativeField("lblZ", value);
			}
		}
	}
}
