// This file has been autogenerated from a class added in the UI designer.
using System;
using Foundation;
using UIKit;
using TransitionsDemo.AnimationControllers;
using TransitionsDemo.InteractionControllers;

namespace TransitionsDemo
{
	public partial class ViewController : UIViewController, IUIViewControllerTransitioningDelegate
	{
		private static nuint colorIndex = 0;
		private NSArray colors;

		[Export ("initWithCoder:")]
		public ViewController (NSCoder coder) : base(coder)
		{
			WeakTransitioningDelegate = this;
		}

		public override void ViewDidLoad ()
		{
			colors = NSArray.FromNSObjects (UIColor.Red, UIColor.Orange, UIColor.Yellow,
			                                UIColor.Green, UIColor.Blue, UIColor.Purple);

			View.BackgroundColor = colors.GetItem<UIColor> (colorIndex);
			colorIndex = (colorIndex + 1) % colors.Count;
		}

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			if (segue.Identifier == "ShowSettings") {
				UIViewController toViewController = segue.DestinationViewController;
				toViewController.WeakTransitioningDelegate = this;
			}

			base.PrepareForSegue (segue, sender);
		}

		[Export ("animationControllerForPresentedController:presentingController:sourceController:")]
		public IUIViewControllerAnimatedTransitioning PresentingController (UIViewController presented,
		                                                                    UIViewController presenting,
		                                                                    UIViewController source)
		{
			if (AppDelegate.SettingsInteractionController != null) {
				AppDelegate.SettingsInteractionController.WireToViewController (presented,
				                                                                CEInteractionOperation.Dismiss);
			}

			if (AppDelegate.SettingsAnimationController != null)
				AppDelegate.SettingsAnimationController.Reverse = false;

			return AppDelegate.SettingsAnimationController;
		}

		[Export ("animationControllerForDismissedController:")]
		public IUIViewControllerAnimatedTransitioning GetAnimationControllerForDismissedController (UIViewController dismissed)
		{
			if (AppDelegate.SettingsAnimationController != null)
				AppDelegate.SettingsAnimationController.Reverse = true;

			return AppDelegate.SettingsAnimationController;
		}
	}
}
