// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace RecaptchaEnterprise
{
	public partial class TitleLabel : UILabel
	{
		public TitleLabel (IntPtr handle) : base (handle)
		{
		}
	}
}
