// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example_StandardControls.Screens.iPhone.PickerView {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("PickerView1_iPhone")]
	public partial class PickerView1_iPhone {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UILabel __mt_lblSelectedItem;
		
		private MonoTouch.UIKit.UIPickerView __mt_pkrMain;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblSelectedItem")]
		private MonoTouch.UIKit.UILabel lblSelectedItem {
			get {
				this.__mt_lblSelectedItem = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lblSelectedItem")));
				return this.__mt_lblSelectedItem;
			}
			set {
				this.__mt_lblSelectedItem = value;
				this.SetNativeField("lblSelectedItem", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("pkrMain")]
		private MonoTouch.UIKit.UIPickerView pkrMain {
			get {
				this.__mt_pkrMain = ((MonoTouch.UIKit.UIPickerView)(this.GetNativeField("pkrMain")));
				return this.__mt_pkrMain;
			}
			set {
				this.__mt_pkrMain = value;
				this.SetNativeField("pkrMain", value);
			}
		}
	}
}
