// This file has been autogenerated from a class added in the UI designer.
using System;
using Foundation;
using UIKit;
using AVFoundation;
using CoreAnimation;
using CoreMedia;
using System.Collections.Generic;

namespace AVCompositionDebugVieweriOS
{
	public class APLCompositionTrackSegmentInfo : NSObject
	{
		public CMTimeRange TimeRange { get; set; }

		public bool Empty { get; set; }

		public string MediaType { get; set; }

		public string Description { get; set; }

		public APLCompositionTrackSegmentInfo (AVCompositionTrackSegment segment, string mediaType)
		{
			if (segment.Empty)
				TimeRange = segment.TimeMapping.Target;
			else
				TimeRange = segment.TimeMapping.Source;

			Empty = segment.Empty;
			MediaType = mediaType;

			NSString url = new NSString (segment.SourceUrl != null ? segment.SourceUrl.AbsoluteString : string.Empty);
			Description = GetDescription (url.LastPathComponent);
		}

		private string GetDescription (string lastPathComponent)
		{
			string description = string.Empty;

			if (!Empty) {
				CMTime startTime = TimeRange.Start;
				CMTime endTime = CMTime.Add (TimeRange.Start, TimeRange.Duration);

				string url = lastPathComponent;

				description = String.Format ("{0:0.0} - {1:0.0}: {2}", startTime.Seconds, endTime.Seconds, url);

				if (MediaType == AVMediaType.Video) 
					description += "(v)";
				else if (MediaType == AVMediaType.Audio) 
					description += "(a)";
				else
					description += String.Format ("({0})", MediaType);
			}

			return description;
		}
	}
}
