// This file has been autogenerated from a class added in the UI designer.
using System;
using System.Collections.Generic;
using CoreGraphics;

using AVFoundation;
using CoreAnimation;
using CoreMedia;
using Foundation;
using UIKit;

namespace AVCompositionDebugVieweriOS
{
	public class APLVideoCompositionStageInfo : NSObject
	{
		public CMTimeRange TimeRange { get; set; }
		public List<string> LayerNames { get; set; }
		public Dictionary<string, List<CGPoint>> OpacityRamps { get; set; }
	}
}
