// This file has been autogenerated from a class added in the UI designer.
using System;
using System.Collections.Generic;
using System.Drawing;

using MonoTouch.AVFoundation;
using MonoTouch.CoreAnimation;
using MonoTouch.CoreMedia;
using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace AVCompositionDebugVieweriOS
{
	public class APLVideoCompositionStageInfo : NSObject
	{
		public CMTimeRange TimeRange { get; set; }
		public List<string> LayerNames { get; set; }
		public Dictionary<string, List<PointF>> OpacityRamps { get; set; }
	}
}
