// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Chat
{
	public partial class OutgoingCell : UITableViewCell
	{
		public OutgoingCell (IntPtr handle) : base (handle)
		{
		}
	}
}
